### PR TITLE
Use RH friendly images

### PR DESCRIPTION
**Pull request by pawanpinjarkar**

### CODE REVIEW

**Comment by andfasano** [comment]
/test e2e-tests

It was just optional, so it could be manually triggered meanwhile I put it back as mandatory

**Comment by derekhiggins** [comment]
thanks, lgtm,  but would you mind squashing both commits into 1

**Comment by andfasano** [comment]
The change looks fine also to me, I'd like to see the e2e-test running first

**Comment by derekhiggins** [comment]
/lgtm
thanks

**Pull request merged**
