### PR TITLE
Ironic: filter nodes by type

### PR DESCRIPTION
**Pull request by derekhiggins**
Use the pool type to select ironic nodes to use

### CODE REVIEW

**Comment by andfasano** [comment]
TBD: add integration test

**Comment by derekhiggins** [comment]
> TBD: add integration test

Thinking about this, an e2e test might be too tricky to implement at the moment as it would require we have ironic setup to use
this provider. Also the e2e tests would need ironic API access to confirm (and possibly update) node details. Can we merge this 
and revisit in future if we have ironic setup for e2e tests.

**Pull request merged**
